version: '3.8'

services:
  assistant-maternel:
    build: .
    ports:
      - "3000:3001"
    volumes:
      - ./data:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    container_name: assistant-maternel

volumes:
  data:
    driver: local